### ISSUE TITLE
In the levels that 'require' a for loop, you are not punished for not using a for loop.

### ISSUE THREAD

**Issue by ghost** [austin-ek/rosette#24]

**Comment by austin-ek** [comment]
Which levels (requiring a loop) is it possible to finish without a loop? The block limits were designed for this purpose.

**Comment by ghost** [comment]
I wasn't able to solve it without a for loop, but I think you should have an error message saying something like "Try using a for loop!" within the error message. Even though it says it in the description, I feel like people will get confused. Maybe it will be more obvious when there is actual documentation explaining what a for loop is (before the first for loop level)

**Comment by austin-ek** [comment]
this error message has been added to the appropriate levels in 2d6fbbb and 00c0c1d
