### ISSUE TITLE
Level 14: One turn block causes the robot to turn twice

### ISSUE THREAD

**Issue by ghost** [austin-ek/rosette#26]
maybe it's me..... D:

![image](https://user-images.githubusercontent.com/23133893/44700947-aa3d0a00-aa51-11e8-9883-dc3119c95837.png)

Screen grab: https://drive.google.com/file/d/15HA8RxbLlEnAfTgCP65e2A9tJd-hSHVH/view?usp=sharing

**Comment by austin-ek** [comment]
The robot is not turning twice. It appeared to do so because when it reset, the rotation happened before the robot was animated back to the original position.

This has since been fixed in 27065da. The rotation now happens after the animation.

Closing this issue
